//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BCGPCalendarDemo.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_RECURRENCE_RULE_WEEKLY      106
#define IDR_MAINFRAME                   128
#define IDR_BCGPCATYPE                  129
#define IDR_POPUP_TOOLBAR               131
#define IDB_WORKSPACE                   147
#define IDB_CAPTION                     150
#define IDB_TOOLBAR256                  151
#define IDD_APP_EDIT_DLG                154
#define IDD_APP_REC_OPEN                155
#define IDR_PLANNER                     156
#define IDD_APP_RECURRENCE              156
#define IDR_PLANNER_DUMMY               158
#define IDB_PLANNER_TB256               159
#define IDR_PLANNER_TIMEBAR             160
#define IDR_PLANNER_CLIENT_MONTH        161
#define IDD_PLANNER_GOTO_DAY            161
#define IDB_PLANNER_DUMMY_TB256         161
#define IDR_PLANNER_CLIENT_WEEK         162
#define IDR_PLANNER_CLIENT_WORK_WEEK    163
#define IDB_CALENDAR_ICONS              163
#define IDB_CALENDAR_CLOCK_C            164
#define IDB_CALENDAR_CLOCK_H            165
#define IDB_CALENDAR_CLOCK_M            166
#define IDI_USERS                       168
#define IDR_PLANNER_APPOINTMENT         169
#define IDI_SECURITY                    169
#define IDR_PLANNER_CLIENT_DAY          170
#define IDR_PLANNER_NEW                 171
#define IDI_PRNTYPE_1                   172
#define IDI_PRNTYPE_2                   173
#define IDI_PRNTYPE_3                   174
#define IDI_PRNTYPE_4                   175
#define IDD_PRNTYPE                     176
#define IDD_APP_REC_DELETE              177
#define IDD_RECURRENCE_RULE_DAILY       178
#define IDD_RECURRENCE_RULE_MONTHLY     179
#define IDD_RECURRENCE_RULE_YEARLY      180
#define IDR_PLANNER_CLIENT_MULTI        181
#define IDR_PLANNER_MULTI               182
#define IDB_PLANNER_MULTI_TB256         183
#define IDD_RESOURCE_EDIT_DLG           184
#define IDC_MAIL                        1000
#define IDC_URL                         1001
#define IDC_VERSION                     1002
#define IDC_MODE_COMBO                  1042
#define IDC_SUBJECT                     1042
#define IDC_LOCATION                    1043
#define IDC_DATETIMEPICKER              1044
#define IDC_LABEL                       1044
#define IDC_PRNTYPE_RADIO1              1045
#define IDC_SHOW_TIME                   1045
#define IDC_PRNTYPE_RADIO2              1046
#define IDC_PRIVATE                     1046
#define IDC_PRNTYPE_RADIO3              1047
#define IDC_MEETING                     1047
#define IDC_PRNTYPE_RADIO4              1048
#define IDC_PHONECALL                   1048
#define IDC_BTN_RECURRENCE              1049
#define IDC_APP_REC_ICON                1050
#define IDC_BTN_DELETE                  1050
#define IDC_APP_REC_RADIO_SERIES        1052
#define IDC_APP_REC_QUEST               1053
#define IDC_APP_REC_RADIO_OCCURRENCE    1054
#define IDC_DATETIME_START_STATIC       1055
#define IDC_DATETIME_END_STATIC         1056
#define IDC_DATETIME_END_STATIC2        1057
#define IDC_RM_DAY                      1057
#define IDC_RULE_MONTHLY                1059
#define IDC_RULE_YEARLY                 1060
#define IDC_DATETIME_START_STATIC2      1061
#define IDC_LIMIT_NONE                  1062
#define IDC_LIMIT_COUNT                 1063
#define IDC_LIMIT_DATE                  1064
#define IDC_COUNT                       1065
#define IDC_RW_SPAN                     1066
#define IDC_REMOVE                      1067
#define IDC_RULE_DAILY                  1068
#define IDC_RM_DAY_SPAN                 1068
#define IDC_RULE_WEEKLY                 1069
#define IDC_RM_DAYTYPE_SPAN             1069
#define IDC_POS_STATIC                  1070
#define IDC_RW_CHECK1                   1071
#define IDC_RW_CHECK2                   1072
#define IDC_RW_CHECK3                   1073
#define IDC_RM_DAYTYPE_NUM              1073
#define IDC_RW_CHECK4                   1074
#define IDC_RM_DAYTYPE_TYPE             1074
#define IDC_DATE_START                  1075
#define IDC_RD_SPAN                     1075
#define IDC_RW_CHECK5                   1075
#define IDC_DATE_END                    1076
#define IDC_RD_TYPE_SPAN                1076
#define IDC_RW_CHECK6                   1076
#define IDC_TIME_START                  1077
#define IDC_RD_TYPE_WEEKDAYS            1077
#define IDC_RW_CHECK7                   1077
#define IDC_TIME_END                    1078
#define IDC_RY_DAY                      1078
#define IDC_DURATION                    1079
#define IDC_RY_DAY_MONTH                1079
#define IDC_RY_DAYTYPE_MONTH            1080
#define IDC_RY_DAY_DAY                  1081
#define IDC_RM_DAY_DAY                  1082
#define IDC_RY_DAYTYPE_TYPE             1083
#define IDC_RY_DAYTYPE_NUM              1084
#define IDC_RM_DAYTYPE                  1085
#define IDC_RY_DAYTYPE                  1086
#define IDC_MEMO                        1087
#define IDC_ALLDAY                      1088
#define IDC_RM_STATIC1                  1089
#define IDC_RM_STATIC2                  1090
#define IDC_RM_STATIC3                  1091
#define IDC_RM_STATIC4                  1092
#define IDC_RY_STATIC1                  1093
#define IDC_DESCRIPTION                 1094
#define IDC_INTERVAL_CHECK              1095
#define IDC_VISIBLE_CHECK               1096
#define ID_VIEW_CUSTOMIZE               32770
#define ID_VIEW_TOOLBARS                32771
#define ID_VIEW_CAPTIONBAR              32816
#define ID_VIEW_APPLOOK_2000            32832
#define ID_VIEW_APPLOOK_XP              32833
#define ID_VIEW_APPLOOK_2003            32834
#define ID_VIEW_APPLOOK_WIN_XP          32835
#define ID_VIEW_APPLOOK_VS2005          32836
#define ID_VIEW_APPLOOK_2007_1          32837
#define ID_VIEW_APPLOOK_2007_2          32838
#define ID_VIEW_APPLOOK_2007_3          32839
#define ID_VIEW_APPLOOK_2007_4          32840
#define ID_VIEW_APPLOOK_VS2008          32841
#define ID_VIEW_CALENDARBAR             32842
#define ID_PLANNER_MODE_DAY             32843
#define ID_PLANNER_MODE_WORKWEEK        32844
#define ID_PLANNER_MODE_WEEK            32845
#define ID_PLANNER_MODE_MONTH           32846
#define ID_PLANNER_TIMELINE_60          32848
#define ID_PLANNER_TIMELINE_30          32849
#define ID_PLANNER_TIMELINE_20          32850
#define ID_PLANNER_TIMELINE_15          32851
#define ID_PLANNER_TIMELINE_10          32852
#define ID_PLANNER_TIMELINE_6           32853
#define ID_PLANNER_TIMELINE_5           32854
#define ID_PLANNER_COMPRESS_WEEKEND     32857
#define ID_PLANNER_GOTO_THISDAY         32858
#define ID_PLANNER_GOTO_TODAY           32860
#define ID_PLANNER_GOTO_DAY             32861
#define ID_PLANNER_DRAW_TIME_AS_ICONS   32868
#define ID_PLANNER_DRAW_TIME_FINISH     32869
#define ID_PLANNER_REMOVE_APP           32870
#define ID_PLANNER_NEW_APPOINTMENT      32871
#define ID_PLANNER_OPEN_APP             32872
#define ID_PLANNER_NEW_REC_APPOINTMENT  32873
#define ID_PLANNER_NEW                  32874
#define ID_VIEW_PROPBAR                 32875
#define ID_PLANNER_NEW_EVENT            32877
#define ID_PLANNER_NEW_REC_EVENT        32878
#define ID_PLANNER_SHOWTOOLTIP          32879
#define ID_PLANNER_MODE_MULTI           32884
#define ID_PLANNER_RESOURCE             32887
#define ID_PLANNER_RESOURCE_ADD         32889
#define ID_PLANNER_RESOURCE_REMOVE      32890
#define ID_PLANNER_RESOURCE_PROP        32891
#define ID_VIEW_PLANNERBAR              32892
#define ID_VIEW_PLANNERMULTIBAR         32893
#define IDS_APPOINTMENT_1               61446
#define IDS_APPOINTMENT_2               61447
#define IDS_APPOINTMENT_3               61448
#define IDS_APPOINTMENT_4               61449
#define IDS_APPOINTMENT_5               61450

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        185
#define _APS_NEXT_COMMAND_VALUE         32894
#define _APS_NEXT_CONTROL_VALUE         1097
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
