//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BCGPOrganizer.rc
//
#define IDB_BUTTONS                     100
#define IDB_CAPTION                     101
#define IDB_CATEGORY_HC                 102
#define IDB_EDITCTRL_LARGE              103
#define IDB_EDITCTRL_SMALL              104
#define IDB_FILE_LARGE                  105
#define IDB_FILE_SMALL                  106
#define IDB_HEADERPAT_1                 107
#define IDB_HEADERPAT_2                 108
#define IDB_HEADERPAT_3                 109
#define IDB_HEADERPAT_4                 110
#define IDB_HOME                        111
#define IDB_INTELLISENSE                112
#define IDB_INTELLISENSE_HC             113
#define IDB_MACROS_FOLDERS              114
#define IDB_MACROS_FONT_HC              115
#define IDB_MACROS_LARGE                116
#define IDB_MACROS_SMALL                117
#define IDB_MACROSEDIT_HC               118
#define IDB_MAIL_BUTTONS                119
#define IDB_MAIL_FLAGS                  120
#define IDB_MAIL_FOLDERS                121
#define IDB_MAIL_HEADER                 122
#define IDB_MAIL_HOME_LARGE             123
#define IDB_MAIL_HOME_SMALL             124
#define IDB_MAIL_ICONS                  125
#define IDB_MAIL_LARGE                  126
#define IDB_MAIL_OPTIONS_LARGE          127
#define IDR_MAINFRAME                   128
#define IDR_BCGPMETYPE                  129
#define IDR_MAILFRAME                   130
#define IDR_APPOINTMENTFRAME            131
#define IDR_TASKFRAME                   132
#define IDB_MAIL_OPTIONS_SMALL          133
#define IDR_GANTTFRAME                  133
#define IDB_MAIL_SEND                   134
#define IDB_MAIL_SMALL                  135
#define IDB_MAIN                        136
#define IDB_MAINFRAME_HC                137
#define IDB_OPTIONS                     138
#define IDB_PLANNER_BUTTONS             139
#define IDB_PLANNER_CLOCK_C             140
#define IDB_PLANNER_CLOCK_H             141
#define IDB_PLANNER_CLOCK_M             142
#define IDB_PLANNER_HC                  143
#define IDB_PLANNER_HOME_LARGE          144
#define IDB_PLANNER_HOME_SMALL          145
#define IDB_PLANNER_ICONS               146
#define IDB_PLANNER_LARGE               147
#define IDB_PLANNER_SMALL               148
#define IDB_SHORTCUTS_LARGE             149
#define IDB_SHORTCUTS_RIBBON_LARGE      150
#define IDB_SHORTCUTS_RIBBON_SMALL      151
#define IDB_SHORTCUTS_SMALL             152
#define IDB_TASKS_HEADER                153
#define IDB_TASKS_ICONS                 154
#define IDB_TASKS_LARGE                 155
#define IDB_TASKS_SMALL                 156
#define IDB_THEME_COLORS                157
#define IDB_THEME_EFFECTS               158
#define IDB_THEME_FONTS                 159
#define IDB_THEME_THEMES                160
#define IDB_TOOLTIP_FONT                161
#define IDB_TOOLTIP_MAIN                162
#define IDB_VIEWPAT_1                   163
#define IDB_VIEWPAT_2                   164
#define IDB_VIEWPAT_3                   165
#define IDB_VIEWPAT_4                   166
#define IDB_WELCOME                     167
#define IDD_APP_DIALOGBAR1              168
#define IDD_APP_DIALOGBAR2              169
#define IDD_APP_EDIT_DLG                170
#define IDD_APP_REC_DELETE              171
#define IDD_APP_REC_OPEN                172
#define IDD_APP_RECURRENCE              173
#define IDD_FINDDIALOG                  174
#define IDD_GOTO_LINE                   175
#define IDD_MAIL_DIALOGBAR1             176
#define IDD_MAIL_DIALOGBAR2             177
#define IDD_OPTIONS_POPULAR_PAGE        178
#define IDD_OPTIONS_RES_PAGE            179
#define IDD_PLANNER_GOTO_DAY            180
#define IDD_PRNTYPE                     181
#define IDD_RECURRENCE_RULE_DAILY       182
#define IDD_RECURRENCE_RULE_MONTHLY     183
#define IDD_RECURRENCE_RULE_WEEKLY      184
#define IDD_RECURRENCE_RULE_YEARLY      185
#define IDI_PRNTYPE_1                   186
#define IDD_GANTT_DIALOGBAR             186
#define IDD_GANTT_DIALOGBAR1            186
#define IDI_PRNTYPE_2                   187
#define IDD_GANTT_DIALOGBAR2            187
#define IDI_PRNTYPE_3                   188
#define IDD_GANTT_GOTO_DAY              188
#define IDI_PRNTYPE_4                   189
#define IDI_REFRESH                     190
#define IDI_SECURITY                    191
#define IDI_USERS                       192
#define IDP_OLE_INIT_FAILED             193
#define IDR_CATEGORY                    194
#define IDR_CATEGORY_MENU               195
#define IDR_EDIT_MENU                   196
#define IDR_EDIT_POPUP_SELECTIONMARGIN  197
#define IDR_EDITCTRL_FONT               198
#define IDR_EDITCTRL_MENU               199
#define IDR_EDITOR_MACROS_1             200
#define IDR_EDITOR_MACROS_2             201
#define IDR_EDITOR_MACROS_3             202
#define IDR_EDITOR_MACROS_4             203
#define IDR_EDITOR_MACROS_5             204
#define IDR_EDITOR_MACROS_6             205
#define IDR_EDITOR_MACROS_7             206
#define IDR_EDITOR_MACROS_8             207
#define IDR_EDITOR_XML_SETTINGS         208
#define IDR_FOLLOW_MENU                 209
#define IDR_FONT_QUALITY                210
#define IDR_MACROS_FONT                 211
#define IDR_MACROSEDIT                  212
#define IDR_MAIL_MENU                   213
#define IDR_OUTPUT_MENU                 214
#define IDR_PASTE_MENU                  215
#define IDR_PLANNER                     216
#define IDR_PLANNER_APPOINTMENT         217
#define IDR_PLANNER_CLIENT_DAY          218
#define IDR_PLANNER_CLIENT_MONTH        219
#define IDR_PLANNER_CLIENT_WEEK         220
#define IDR_PLANNER_CLIENT_WORK_WEEK    221
#define IDR_PLANNER_GOTO                222
#define IDR_PLANNER_NEW                 223
#define IDR_PLANNER_TIMEBAR             224
#define IDR_PLANNER_TIMESCALE           225
#define IDR_TASKS_MENU                  226
#define IDR_THEME_MENU                  227
#define IDS_APPOINTMENT_1               228
#define IDR_GANTT_EVENT                 228
#define IDR_GANTT_TASK                  228
#define IDS_APPOINTMENT_2               229
#define IDR_GANTT_CLIENT                229
#define IDS_APPOINTMENT_3               230
#define IDS_APPOINTMENT_4               231
#define IDS_APPOINTMENT_5               232
#define IDS_CARET_POS                   233
#define IDS_DUMMY_UNDO_ACTION           234
#define IDS_EDITFAILED                  235
#define IDS_PGUPFAILED                  236
#define IDS_STRING_NOT_FOUND_FMT        237
#define IDS_UAT_BACKSPACE               238
#define IDS_UAT_CUT                     239
#define IDS_UAT_DELETE                  240
#define IDS_UAT_DRAGDROP                241
#define IDS_UAT_ENTER                   242
#define IDS_UAT_INDENT                  243
#define IDS_UAT_PASTE                   244
#define IDS_UAT_REPLACE                 245
#define IDS_UAT_TAB                     246
#define IDS_UAT_TYPING                  247
#define IDS_UAT_UNDEFINED               248
#define IDS_UAT_UNINDENT                249
#define IDS_UAT_UNKNOWN                 250
#define IDB_MAIL_FILE_SMALL             251
#define IDB_MAIL_FILE_LARGE             252
#define IDB_PLANNER_FILE_SMALL          253
#define IDB_PLANNER_FILE_LARGE          254
#define IDB_GANTT_SMALL                 255
#define IDB_GANTT_LARGE                 256
#define IDR_SHOWAS                      257
#define IDR_SHOWAS_MENU                 260
#define IDB_SHOWAS_HC                   261
#define IDR_GANTT_NEW                   261
#define IDI_COMPLETE                    262
#define IDR_GANTT_GOTO                  262
#define IDB_GANTT_HOME_SMALL            263
#define IDI_MILESTONE                   264
#define IDB_GANTT_BUTTONS               265
#define IDI_MILESTONE_COMPLETE          266
#define IDB_GANTT_FILE_LARGE            267
#define IDB_GANTT_FILE_SMALL            268
#define IDB_GANTT_HOME_LARGE            269
#define IDS_GANTT_1                     270
#define IDR_GANTT                       271
#define IDB_GANTT_HC                    272
#define IDC_APP_EDIT_DATE_END           1041
#define IDC_APP_EDIT_DATE_START         1042
#define IDC_APP_EDIT_DATETIME_END_STATIC 1043
#define IDC_APP_EDIT_DATETIME_START_STATIC 1044
#define IDC_APP_EDIT_LABEL              1045
#define IDC_APP_EDIT_LOCATION           1046
#define IDC_APP_EDIT_MEETING            1047
#define IDC_APP_EDIT_MEMO               1048
#define IDC_APP_EDIT_PHONECALL          1049
#define IDC_APP_EDIT_SEPARATOR          1050
#define IDC_APP_EDIT_SHOW_TIME          1051
#define IDC_APP_EDIT_SUBJECT            1052
#define IDC_APP_EDIT_TIME_END           1053
#define IDC_APP_EDIT_TIME_START         1054
#define IDC_APP_REC_ICON                1055
#define IDC_APP_REC_QUEST               1056
#define IDC_APP_REC_RADIO_OCCURRENCE    1057
#define IDC_APP_REC_RADIO_SERIES        1058
#define IDC_BANER                       1059
#define IDC_COLOR_SCHEME                1060
#define IDC_COMPANY_URL                 1061
#define IDC_CONTACT                     1062
#define IDC_COUNT                       1063
#define IDC_DATE_END                    1064
#define IDC_DATE_START                  1065
#define IDC_DATETIME_END_STATIC         1066
#define IDC_DATETIME_END_STATIC2        1067
#define IDC_DATETIME_START_STATIC       1068
#define IDC_DATETIME_START_STATIC2      1069
#define IDC_DATETIMEPICKER              1070
#define IDC_DURATION                    1071
#define IDC_FINDDIALOG_DOWNRADIO        1072
#define IDC_FINDDIALOG_FINDCOMBO        1073
#define IDC_FINDDIALOG_MARKALLBUTTON    1074
#define IDC_FINDDIALOG_MATCHCASECHECK   1075
#define IDC_FINDDIALOG_MATCHWHOLEWORDONLYCHECK 1076
#define IDC_FINDDIALOG_REGULARBUTTON    1077
#define IDC_FINDDIALOG_REGULAREXPRESSIONCHECK 1078
#define IDC_FINDDIALOG_SEARCHALLOPENDOCUMENTSCHECK 1079
#define IDC_FINDDIALOG_UPRADIO          1080
#define IDC_GOTO_LINE_LINE              1081
#define IDC_HOME                        1082
#define IDC_LIMIT_COUNT                 1083
#define IDC_LIMIT_DATE                  1084
#define IDC_LIMIT_NONE                  1085
#define IDC_MAIL_EDIT_CC                1086
#define IDC_MAIL_EDIT_FROM              1087
#define IDC_MAIL_EDIT_SUBJECT           1088
#define IDC_MAIL_EDIT_TO                1089
#define IDC_MODE_COMBO                  1090
#define IDC_POS_STATIC                  1091
#define IDC_PRNTYPE_RADIO1              1092
#define IDC_PRNTYPE_RADIO2              1093
#define IDC_PRNTYPE_RADIO3              1094
#define IDC_PRNTYPE_RADIO4              1095
#define IDC_PRODUCT                     1096
#define IDC_RD_SPAN                     1097
#define IDC_RD_TYPE_SPAN                1098
#define IDC_RD_TYPE_WEEKDAYS            1099
#define IDC_REMOVE                      1100
#define IDC_RM_DAY                      1101
#define IDC_RM_DAY_DAY                  1102
#define IDC_RM_DAY_SPAN                 1103
#define IDC_RM_DAYTYPE                  1104
#define IDC_RM_DAYTYPE_NUM              1105
#define IDC_RM_DAYTYPE_SPAN             1106
#define IDC_RM_DAYTYPE_TYPE             1107
#define IDC_RM_STATIC1                  1108
#define IDC_RM_STATIC2                  1109
#define IDC_RM_STATIC3                  1110
#define IDC_RM_STATIC4                  1111
#define IDC_RULE_DAILY                  1112
#define IDC_RULE_MONTHLY                1113
#define IDC_RULE_WEEKLY                 1114
#define IDC_RULE_YEARLY                 1115
#define IDC_RW_CHECK1                   1116
#define IDC_RW_CHECK2                   1117
#define IDC_RW_CHECK3                   1118
#define IDC_RW_CHECK4                   1119
#define IDC_RW_CHECK5                   1120
#define IDC_RW_CHECK6                   1121
#define IDC_RW_CHECK7                   1122
#define IDC_RW_SPAN                     1123
#define IDC_RY_DAY                      1124
#define IDC_RY_DAY_DAY                  1125
#define IDC_RY_DAY_MONTH                1126
#define IDC_RY_DAYTYPE                  1127
#define IDC_RY_DAYTYPE_MONTH            1128
#define IDC_RY_DAYTYPE_NUM              1129
#define IDC_RY_DAYTYPE_TYPE             1130
#define IDC_RY_STATIC1                  1131
#define IDC_SCREENTIP_STYLE             1132
#define IDC_SHORTCUTSBAR_MACROS         1133
#define IDC_SHORTCUTSBAR_MAIL           1134
#define IDC_SHORTCUTSBAR_PLANNER        1135
#define IDC_SHORTCUTSBAR_SHORTCUTS      1136
#define IDC_SHORTCUTSBAR_TASKS          1137
#define IDC_SHOW_FLOATY                 1138
#define IDC_SHOW_KEY_TIPS               1139
#define IDC_SUPPORT                     1140
#define IDC_TIME_END                    1141
#define IDC_TIME_START                  1142
#define IDC_SHORTCUTSBAR_GANTT          1143
#define IDC_GANTT_EDIT_NAME             1144
#define IDC_GANTT_EDIT_DATE_START       1145
#define IDC_GANTT_EDIT_DATE_END         1146
#define IDC_GANTT_EDIT_TIME_START       1147
#define IDC_GANTT_EDIT_TIME_END         1148
#define IDC_GANTT_EDIT_LABEL            1149
#define IDC_GANTT_EDIT_SEPARATOR        1150
#define IDC_GANTT_EDIT_PROGRESS         1151
#define IDC_GANTT_EDIT_PROGRESS_SPIN    1152
#define ID_APP_EDIT_ALLDAY              32787
#define ID_APP_EDIT_DELETE              32788
#define ID_APP_EDIT_IMPORTANCE_HIGH     32789
#define ID_APP_EDIT_IMPORTANCE_LOW      32790
#define ID_APP_EDIT_PRIVATE             32791
#define ID_APP_EDIT_RECURRENCE          32792
#define ID_APP_EDIT_SAVE_CLOSE          32793
#define ID_CATEGORY_1                   32794
#define ID_CATEGORY_2                   32795
#define ID_CATEGORY_3                   32796
#define ID_CATEGORY_4                   32797
#define ID_CATEGORY_5                   32798
#define ID_CATEGORY_6                   32799
#define ID_DUMMY                        32800
#define ID_DUMMY_REMOVE_ALL_BREAKPOINTS 32801
#define ID_EDIT_AUTOOUTLINING           32802
#define ID_EDIT_CLEAR_ALLBOOKMARKS      32803
#define ID_EDIT_COLLAPSETODEFINITIONS   32804
#define ID_EDIT_DECREASE_IDENT          32805
#define ID_EDIT_ENABLEOUTLINING         32806
#define ID_EDIT_FIND_COMBO              32807
#define ID_EDIT_FINDNEXT                32808
#define ID_EDIT_FINDPREV                32809
#define ID_EDIT_GOTO_LINE               32810
#define ID_EDIT_HIDESELECTION           32811
#define ID_EDIT_INCREASE_IDENT          32812
#define ID_EDIT_LINENUMBERS             32813
#define ID_EDIT_LISTMEMBERS             32814
#define ID_EDIT_NEXT_WORD               32815
#define ID_EDIT_NEXTBOOKMARK            32816
#define ID_EDIT_PARA_BULLETS            32817
#define ID_EDIT_PARA_CENTER             32818
#define ID_EDIT_PARA_LEFT               32819
#define ID_EDIT_PARA_RIGHT              32820
#define ID_EDIT_PREVIOUSBOOKMARK        32821
#define ID_EDIT_SHOWHINT                32822
#define ID_EDIT_STOPHIDINGCURRENT       32823
#define ID_EDIT_STOPOUTLINING           32824
#define ID_EDIT_TOGGLEALLOUTLINING      32825
#define ID_EDIT_TOGGLEBOOKMARK          32826
#define ID_EDIT_TOGGLEBREAKPOINT        32827
#define ID_EDIT_TOGGLEOUTLINING         32828
#define ID_FILE_PREPARE                 32829
#define ID_FILE_PREPARE_ADD_SIGNATURE   32830
#define ID_FILE_PREPARE_ENCRYPT         32831
#define ID_FILE_PREPARE_INSPECT         32832
#define ID_FILE_PREPARE_MARK_AS_FINAL   32833
#define ID_FILE_PREPARE_PROPERTIES      32834
#define ID_FILE_PREPARE_RUN_CHECKER     32835
#define ID_FILE_PUBLISH                 32836
#define ID_FILE_PUBLISH_BLOG            32837
#define ID_FILE_PUBLISH_CREATE_DOCWORKSPACE 32838
#define ID_FILE_PUBLISH_DOCMANAGE_SERVER 32839
#define ID_FILE_SAVE_AS_ADDINS          32840
#define ID_FILE_SAVE_AS_DOCUMENT        32841
#define ID_FILE_SAVE_AS_DOCUMENT_OLD    32842
#define ID_FILE_SAVE_AS_OTHER           32843
#define ID_FILE_SAVE_AS_TEMPLATE        32844
#define ID_FILE_SEND                    32845
#define ID_FILE_SEND_EMAIL              32846
#define ID_FILE_SEND_FAX                32847
#define ID_FOLLOW_1                     32848
#define ID_FOLLOW_2                     32849
#define ID_FOLLOW_3                     32850
#define ID_FOLLOW_4                     32851
#define ID_FOLLOW_5                     32852
#define ID_FOLLOW_6                     32853
#define ID_FONT_BOLD                    32854
#define ID_FONT_BOX                     32855
#define ID_FONT_CHANGECASE              32856
#define ID_FONT_CLEARFORMAT             32857
#define ID_FONT_COLOR                   32858
#define ID_FONT_DECREASE                32859
#define ID_FONT_FONT                    32860
#define ID_FONT_INCREASE                32861
#define ID_FONT_ITALIC                  32862
#define ID_FONT_QUALITY                 32863
#define ID_FONT_QUALITY_ANTIALIAZED     32864
#define ID_FONT_QUALITY_CLEARTYPE       32865
#define ID_FONT_QUALITY_DEFAULT         32866
#define ID_FONT_QUALITY_NONANTIALIAZED  32867
#define ID_FONT_SIZE                    32868
#define ID_FONT_STRIKETHROUGH           32869
#define ID_FONT_SUBSCRIPT               32870
#define ID_FONT_SUPERSCRIPT             32871
#define ID_FONT_TEXTHIGHLIGHT           32872
#define ID_FONT_UNDERLINE               32873
#define ID_GRID_VIEW_COLLAPSE_ALL       32874
#define ID_GRID_VIEW_COLUMN_AUTO_RESIZE 32875
#define ID_GRID_VIEW_EXPAND_ALL         32876
#define ID_GRID_VIEW_FIELDCHOOSER       32877
#define ID_GRID_VIEW_GROUPBOX           32878
#define ID_MAIL_EDIT_ACTIONS            32879
#define ID_MAIL_EDIT_ATTACH_FILE        32880
#define ID_MAIL_EDIT_ATTACH_ITEM        32881
#define ID_MAIL_EDIT_BUSINESS_CARD      32882
#define ID_MAIL_EDIT_CALENDAR           32883
#define ID_MAIL_EDIT_CC                 32884
#define ID_MAIL_EDIT_DELETE             32885
#define ID_MAIL_EDIT_FOLLOW             32886
#define ID_MAIL_EDIT_FORMAT_HTML        32887
#define ID_MAIL_EDIT_FORMAT_PLAIN       32888
#define ID_MAIL_EDIT_FORMAT_RTF         32889
#define ID_MAIL_EDIT_FORWARD            32890
#define ID_MAIL_EDIT_IMPORTANCE_HIGH    32891
#define ID_MAIL_EDIT_IMPORTANCE_LOW     32892
#define ID_MAIL_EDIT_LABEL              32893
#define ID_MAIL_EDIT_MARK_AS_UNREAD     32894
#define ID_MAIL_EDIT_MOVE               32895
#define ID_MAIL_EDIT_PRIVATE            32896
#define ID_MAIL_EDIT_REPLY              32897
#define ID_MAIL_EDIT_REPLY_ALL          32898
#define ID_MAIL_EDIT_SAVE_CLOSE         32899
#define ID_MAIL_EDIT_SEND               32900
#define ID_MAIL_EDIT_SHOW_BCC           32901
#define ID_MAIL_EDIT_SHOW_FROM          32902
#define ID_MAIL_EDIT_SIGNATURE          32903
#define ID_MAIL_EDIT_TO                 32904
#define ID_MAIL_FIND                    32905
#define ID_MAIL_NAMES_AB                32906
#define ID_MAIL_NAMES_CHECK             32907
#define ID_MAIL_NEW                     32908
#define ID_MAIL_REMOVE                  32909
#define ID_MAIN                         32910
#define ID_PAGELAYOUT_COLORS            32911
#define ID_PAGELAYOUT_COLORS_CREATENEWTHEMECOLORS 32912
#define ID_PAGELAYOUT_EFFECTS           32913
#define ID_PAGELAYOUT_FONTS             32914
#define ID_PAGELAYOUT_FONTS_CREATENEWTHEMEFONTS 32915
#define ID_PAGELAYOUT_PAGEBACKGROUND_PAGECOLOR 32916
#define ID_PAGELAYOUT_THEMES            32917
#define ID_PAGELAYOUT_THEMES_BROWSEFORTHEMES 32918
#define ID_PAGELAYOUT_THEMES_MORETHEMES 32919
#define ID_PAGELAYOUT_THEMES_RESETFROMTEMPLATE 32920
#define ID_PAGELAYOUT_THEMES_SAVECURRENTTHEME 32921
#define ID_PLANNER_COMPRESS_WEEKEND     32922
#define ID_PLANNER_DRAW_APP_DURATION    32923
#define ID_PLANNER_DRAW_APP_GRADIENT    32924
#define ID_PLANNER_DRAW_APP_ROUNDED     32925
#define ID_PLANNER_DRAW_TIME_AS_ICONS   32926
#define ID_PLANNER_DRAW_TIME_FINISH     32927
#define ID_GOTO_DAY                     32928
#define ID_GOTO_THISDAY                 32929
#define ID_GOTO_TODAY                   32930
#define ID_PLANNER_MODE_DAY             32931
#define ID_PLANNER_MODE_MONTH           32932
#define ID_PLANNER_MODE_WEEK            32933
#define ID_PLANNER_MODE_WORKWEEK        32934
#define ID_PLANNER_NEW                  32935
#define ID_PLANNER_NEW_APPOINTMENT      32936
#define ID_PLANNER_NEW_EVENT            32937
#define ID_PLANNER_NEW_REC_APPOINTMENT  32938
#define ID_PLANNER_NEW_REC_EVENT        32939
#define ID_PLANNER_OPEN_APP             32940
#define ID_PLANNER_REMOVE_APP           32941
#define ID_PLANNER_SHOWTOOLTIP          32942
#define ID_PLANNER_TIMELINE_5           32943
#define ID_PLANNER_TIMELINE_6           32944
#define ID_PLANNER_TIMELINE_10          32945
#define ID_PLANNER_TIMELINE_15          32946
#define ID_PLANNER_TIMELINE_20          32947
#define ID_PLANNER_TIMELINE_30          32948
#define ID_PLANNER_TIMELINE_60          32949
#define ID_PLANNER_TIMESCALE            32950
#define ID_SHORTCUTS_ABOUT              32951
#define ID_SHORTCUTS_DOWNLOAD           32952
#define ID_SHORTCUTS_HOME               32953
#define ID_SHORTCUTS_MAIL               32954
#define ID_STATUSBAR_PAGE               32955
#define ID_STATUSBAR_PROGRESS           32956
#define ID_STATUSBAR_REFRESH            32957
#define ID_STATUSBAR_ZOOM               32958
#define ID_STATUSBAR_ZOOM_SLIDER        32959
#define ID_TASKS_MARK_COMPLETE          32960
#define ID_TASKS_NEW                    32961
#define ID_TASKS_OPEN                   32962
#define ID_TASKS_REMOVE                 32963
#define ID_TASKS_SHOW_ALL               32964
#define ID_TASKS_SHOW_TASKS             32965
#define ID_TASKS_SHOW_TODO              32966
#define ID_TOOLS_OPTIONS                32967
#define ID_VIEW_APPLOOK                 32968
#define ID_VIEW_APPLOOK_2007_1          32969
#define ID_VIEW_APPLOOK_2007_2          32970
#define ID_VIEW_APPLOOK_2007_3          32971
#define ID_VIEW_APPLOOK_2007_4          32972
#define ID_VIEW_BAR_CAPTION             32973
#define ID_VIEW_BAR_OUTPUT              32974
#define ID_VIEW_BAR_SHORTCUTS           32975
#define ID_PLANNER_DRAW_BACKGROUND      32976
#define ID_GANTT_OPEN_TASK              32977
#define ID_GANTT_REMOVE_TASK            32978
#define ID_GANTT_NEW_TASK               32979
#define ID_SHOWAS_1                     32980
#define ID_SHOWAS_2                     32981
#define ID_SHOWAS_3                     32982
#define ID_SHOWAS_4                     32983
#define ID_GANTT_DRAW_BACKGROUND        32984
#define ID_GANTT_EDIT_DELETE            32985
#define ID_GANTT_EDIT_SAVE_CLOSE        32986
#define ID_GANTT_EDIT_PRIVATE           32987
#define ID_GANTT_EDIT_IMPORTANCE_HIGH   32988
#define ID_GANTT_EDIT_IMPORTANCE_LOW    32989
#define ID_GANTT_NEW_MILESTONE          32990
#define ID_GANTT_NEW                    32991
#define ID_GANTT_MARK_COMPLETE          32992
#define ID_GANTT_LINK                   32995
#define ID_GANTT_UNLINK                 32996
#define ID_ACTIVATE_VIEW_0              33100
#define ID_ACTIVATE_VIEW_1              33101
#define ID_ACTIVATE_VIEW_2              33102
#define ID_ACTIVATE_VIEW_3              33103
#define ID_ACTIVATE_VIEW_4              33104
#define ID_ACTIVATE_VIEW_5              33105

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        273
#define _APS_NEXT_COMMAND_VALUE         32997
#define _APS_NEXT_CONTROL_VALUE         1153
#define _APS_NEXT_SYMED_VALUE           1244
#endif
#endif
